name: RailRoad CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      # Runs a set of commands using the runners shell
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Build with Gradle
        run: ./gradlew
